<a href="https://colab.research.google.com/github/Rafaelsaraujo/AnaliseDeDados/blob/master/Python3_atividade01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importando o numpy
import numpy as np

In [7]:
# Criando lista de 0 a 15
lista1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
lista1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [9]:
# Convertendo a lista para Array
array1 = np.array(lista1)
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
# Criando a mesma lista com os recursos Numpy
lista1 = np.arange(16)
lista1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# Array de 10 "zeros"
array0 = np.zeros(10)
array0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# Array de 10 "ones"
array11 = np.ones(10)
array11

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
# Array de 10 "fives"
array5 = np.ones(10) * 5
array5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
# Array de inteiros de 10 a 50
lista10a50 = np.arange(10, 51)
lista10a50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [22]:
# Matriz 3x3
lista3x3 = ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
myMatrix = np.matrix(lista3x3)
myMatrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])