<a href="https://colab.research.google.com/github/Rafaelsaraujo/AnaliseDeDados/blob/master/Python3_Aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# data science - transformação de dados em informações úteis e aplicadas estrategicamente
# big data - GRANDES conjuntos de dados - Volume, Variedade, Velocidade, Veracidade e Valor

# Média, Moda e Mediana
# Variância = Variação de valores dentro da amostragem

In [ ]:
# Numpy - Biblioteca Python. Principalmente usada pra usar Arrays multidimensionais
# Modelos de Machine learning
# Processamento de imagem e computação gráfica

In [2]:
import numpy as np

In [ ]:
# Criando uma lista e colocando o nome da lista abaixo pra conferir
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
# Transformando essa lista em um array numpy
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# outras formas de criar essa mesma lista
minhaLista = list(range(9))
print(minhaLista)

array1 = np.array(range(9))
print(array1)

array2 = np.arange(9)
print(array2)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]


In [ ]:
# Start, Stop and Step
array3 = np.arange(0, 10, 0.5)
print(array3)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
# Arredondando valores obtidos
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [ ]:
# Também podemos forçar o tipo dos elementos
array3 = np.arange(0, 10, 0.5, dtype=int)
print(array3)

array4 = np.arange(0, 10, 0.5, dtype=float)
print(array4)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
#Podemos pré determinar o tipo dos elementos
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
# Acima, teremos números inteiros, mas posso deixar mey array previamente preparado para trabalhar futuramente com tipos float
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
# Verificando o tipo do objeto
type(array4)

numpy.ndarray

In [ ]:
# Verificando o tipo dos elementos do array
array4.dtype #ou usando print
#print(array4.dtype)

dtype('int64')

In [ ]:
# criar um array digitando os valores
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [ ]:
# selecionando um elemento específico
vetor1[3]

3

In [ ]:
# selecionando um intervalo específico
vetor1[0:2]
#ou print(vetor[0:2])

array([0, 1])

In [ ]:
# Criando um array de strings
s = np.array(['Python','Profissional', 'Java', "Água"])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [ ]:
s = np.array(['Python', 123456789, 'Profissional', 'Java', "Água"])
s

array(['Python', '123456789', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [ ]:
# Alterando um elemento no array
#INT POR INT
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
#Vamos tentar incluir elementos
# int por string
vetor1[0] = 'novo elemento'
vetor1

In [ ]:
# Agora tente o seguinte
#int por float
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])

In [ ]:
#Ja tinha um tipo int, e não da pra substituir por qualquer outro tipo

In [ ]:
# Criando a primeira Matriz
minhaMatriz = np.array([[1, 2, 3],
                        [4, 5, 6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#Lembrando que você pode escrever apenas assim
minhaMatriz = np.array([[1, 2, 3], [4, 5, 6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Podemos criar uma matriz a partir de uma lista
minhaLista = [[12, 81, 22], [0, 34, 59], [21, 48, 94]]
minhaLista

[[12, 81, 22], [0, 34, 59], [21, 48, 94]]

In [ ]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[12, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [ ]:
# np.zeros: pode formar vetores e matrizes
# vetor:

x = np.zeros(3)
x

array([0., 0., 0.])

In [ ]:
# Matriz
x = np.zeros((3, 2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# Consegue fazer sem armazenar em variáveis
#vetor:
print(np.zeros(3))
print(np.zeros((3, 2)))

[0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#np.ones
x = np.ones((5, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Igualmente é possível para apenas um vetor
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

In [ ]:
# DESAFIO: como obter uma matriz 4x4 apenas com números 8?

m = np.ones((4, 4)) * 8
m

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [ ]:
#np.diag para formar matrizes
#os valores passados como parametros formam uma diagonal
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
# np.eye para formar matrizes
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Agora, determinando o tipo int
y = np.eye(5, dtype=int) *5
y

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
# Verificando o shape(forma) de duas maneiras
np.shape(minhaMatriz)

(3, 3)

In [ ]:
#OU
minhaMatriz.shape

(3, 3)

In [ ]:
# Verificando o tipo da matriz
type(minhaMatriz)

numpy.matrix

In [ ]:
#Verificando o tipo dos dados dentro da matriz
minhaMatriz.dtype

dtype('int64')

In [ ]:
#Selecionando elementos de uma matriz
print(minhaMatriz)
minhaMatriz[2, 1]


[[12 81 22]
 [ 0 34 59]
 [21 48 94]]


48

In [ ]:
# Selecionando a primeira linha toda
print(minhaMatriz[0, :])

[[12 81 22]]


In [ ]:
#Selecionando a terceira coluna
print(minhaMatriz[:, 2])

[[22]
 [59]
 [94]]


In [ ]:
#Alterando um elemento da Matriz
minhaMatriz[1, 0] = 100
minhaMatriz

matrix([[ 12,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [ ]:
# OBS:  É SEMPRE LINHA - COLUNA

In [ ]:
# Obtendo a soma dos valores do array
np.sum(meuArray)

36

In [ ]:
# Obtendo produto
np.prod(meuArray)

0

In [ ]:
# Obtendo a soma acumulada
print(meuArray)
np.cumsum(meuArray)

[0 1 2 3 4 5 6 7 8]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [ ]:
# Obtendo valor mínimo do array
meuArray.min()

0

In [ ]:
#Obtendo valor maximo
meuArray.max()

8

In [ ]:
#Obtendo a média dos valors do array
np.mean(meuArray)

4.0

In [ ]:
#Obtendo a mediana
np.median(meuArray)

4.0

In [ ]:
# obtendo a variância dos valores:
np.var(meuArray)

6.666666666666667

In [ ]:
#Obtendo o desvio padrão dos valores
np.std(meuArray)

2.581988897471611

In [3]:
#Desafio
#criar array unidimensional usando range 20 elementos
des1 = np.arange(20)
des1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# Varrer o array para obter os pares
des1[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
# varrer e obter os ímpares
des1[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#obter a média, a soma, o produto, a variancia e o desvio padrão do array
np.sum(des1)
np.mean(des1)
np.var(des1)
np.std(des1)
np.median(des1)

9.5

In [ ]:
# Saber se os valores são maiores do que 5

for y in x:
  if y > 5:
    print(y)

In [ ]:
#obter os valores são maiores do q 5
print(des1[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
